import argparse
from collections import Counter
from cyvcf2 import VCF, Writer
import pysam
import sys
import os
import subprocess
from pybedtools import BedTool
from aam_mod import cooper
import random

import Levenshtein as lv


tool_choices = ["strkit", "strdust", "longtr", "atarva", "medaka", "strkitrr", "vamos", "straglr"] # no support for vamos for now


def parse_args():
    parser = argparse.ArgumentParser(description="Compare assembly-based genotypes with variant calls in the tool.")

    input_args = parser.add_mutually_exclusive_group(required=True)
    input_args.add_argument("-v", "--vcf",   type=str, help="VCF file generated by a TR genotyper tool.")
    input_args.add_argument("-i", "--input", type=argparse.FileType('r'), help="A tab-delimited file containing the following columns: sample_id, vcf_path, mat_aln, pat_aln, karyotype.")

    parser.add_argument("-k", "--karyotype", type=str, help="Karyotype information for the sample, in the format 'XX' or 'XY'.")
    parser.add_argument("-a", "--aln", nargs=2, type=str, metavar=('MAT_ALN','PAT_ALN'),
                        help="Alignment files of maternal and paternal assemblies with reference.")
    parser.add_argument("-bed", "--regions", type=str, default=None, help="BED file containing TR regions to analyze.")
    parser.add_argument("-t", "--tool", required=True, type=str, choices=tool_choices, default="atarva", help="TR genotyping tool used.")
    parser.add_argument("-r", "--reference", type=str, default=None, help="Reference genome FASTA file used for alignments.")
    parser.add_argument("-s", "--sample-id", type=str, default='Sample', help="Sample name.")

    optional_args = parser.add_argument_group("Optional Arguments")
    optional_args.add_argument("-o", "--output", type=argparse.FileType("w"), default=sys.stdout, help="Output file to write concordance results. Default: concordance_results.txt")
    optional_args.add_argument("--catalogue-coords", action="store_true", default=False, help="Whether to check the concordance strictly within the coordinates given in the catalogue.")

    args = parser.parse_args()

    if args.vcf and args.karyotype == None:
        parser.error("--vcf requires --karyotype to be specified.")
    if args.vcf and args.aln == None:
        parser.error("--vcf requires --aln to be specified.")

    if args.catalogue_coords and args.regions == None:
        parser.error("--catalogue-coords requires --regions to be specified.")

    return args


def get_assembly_genotypes(mat_aln, pat_aln, _bgz_bed, karyotype='XX'):
    """
    Get the locus genotypes from maternal and paternal assemblies.

    :param mat_aln: pysam.AlignmentFile object for maternal assembly
    :param pat_aln: pysam.AlignmentFile object for paternal assembly
    :param _bgz_bed: bgzipped and tabix-indexed BED file containing TR regions
    :return: Dictionary with locus as key and genotype (list of two allele lengths) as value
    """

    mat_alleles = cooper(mat_aln, _bgz_bed, 5, 0)
    pat_alleles = cooper(pat_aln, _bgz_bed, 5, 0)
    
    loci = list(set(mat_alleles.keys()).union(set(pat_alleles.keys())))
    assembly_genotypes = {}
    for locus in loci:
        chrom = locus.split('-')[0]
        mat_allele = None if locus not in mat_alleles else mat_alleles[locus][2]
        pat_allele = None if locus not in pat_alleles else pat_alleles[locus][2]
        if chrom == 'chrX' and karyotype == 'XY':
            if mat_allele is not None: assembly_genotypes[locus] = [mat_allele]
            elif pat_allele is not None: assembly_genotypes[locus] = [pat_allele]
            else: pass
        elif chrom == 'chrY' and karyotype == 'XY':
            if pat_allele is not None: assembly_genotypes[locus] = [pat_allele]
            elif mat_allele is not None: assembly_genotypes[locus] = [mat_allele]
            else: pass
        else:
            if mat_allele is not None and pat_allele is not None:
                assembly_genotypes[locus] = [mat_allele, pat_allele] if len(mat_allele) <= len(pat_allele) else [pat_allele, mat_allele]

    return assembly_genotypes


def get_locus_key(var, tool):
    """
    Get a unique locus key based on the tool used.

    :param var: cyvcf2.Variant object
    :param tool: Tool name as string
    :return: Locus key as string
    """
    if tool == "longtr":
        try:
            return '-'.join(var.ID.split('-')[:3])
        except:
            return f"{var.CHROM}-{var.INFO['START']}-{var.INFO['END']}"
    if tool == "strkit": return f"{var.CHROM}-{var.INFO['BED_START']}-{var.INFO['BED_END']}"
    if tool == "atarva": return f"{var.CHROM}-{var.INFO['START']}-{var.INFO['END']}"
    if tool == "medaka": return '-'.join(var.ID.split('_')[:3])
    if tool == "vamos": return f"{var.CHROM}-{var.start+1}-{var.INFO['END']+1}"
    if tool == "strdust": return f"{var.CHROM}-{var.start}-{var.INFO['END']}"
    if tool == "straglr": return f"{var.CHROM}-{var.start+1}-{var.INFO['END']}"
    return None


def parse_info(info, info_data):
    """
    Parse the INFO field of a VCF entry and populate the info_data dictionary.

    :param info: INFO field string from VCF
    :param info_data: Dictionary to populate with parsed INFO data
    :return: None
    """

    for item in info.split(';'):
        key, value = item.split('=')
        info_data[key] = value


def process_vcf(vcf, tool, locus_motif, karyotype='XX'):
    """
    Process the VCF file to extract variant information and genotypes.

    :param vcf: Path to VCF file
    :param tool: Tool name as string
    :param karyotype: Karyotype as string ('XX' or 'XY')
    :return: Tuple of (list of BED entries, dictionary of tool genotypes, dictionary of locus keymap)
    """
    tool_genotypes = {}
    bed_entries    = []
    locus_keymap   = {}
    motif = ''
    for v in VCF(vcf): # or VCF('some.bcf')
        ref = v.REF
        alt = v.ALT

        chrom = v.CHROM
        start = v.start

        # this is because atarva generates 0-based VCF files
        if tool == 'vamos': start += 1
        end = start + len(ref)      # v.end is also available but is taken from END INFO field
        if tool == 'strkit' and start + 1 == v.INFO['BED_START'] and end == v.INFO['BED_END']: start += 1  # strkit offsets the variant coordinates by 1

        if tool == 'straglr':
            start += 1; end = v.INFO['END']

        bed_entries.append((chrom, start, end))
        bed_key = get_locus_key(v, tool)
        if   tool == 'atarva' or tool == 'longtr' or tool == 'strkit': motif = v.INFO['MOTIF']
        elif tool == 'vamos': motif = v.INFO['RU']

        haploid = False

        if not v.genotypes: continue

        alleles = [ref] + [a for a in alt]
        if tool == 'strkit' and v.start + 1 == v.INFO['BED_START'] and end == v.INFO['BED_END']:
            alleles = [ref[1:]] + [a[1:] for a in alt]
        if tool == 'straglr':
            info = {}
            for i in v.INFO: info[i[0]] = i[1]
            allele_lengths = [end - start]
            if 'RB' not in info: pass
            else:
                if type(info['RB']) == int or (type(info['RB']) == str and ',' not in info['RB']):
                    allele_lengths.append(int(info['RB']))
                else:
                    for l in info['RB']:
                        allele_lengths.append(int(l))
            alleles = ['X'*l for l in allele_lengths]

        tool_genotype = []
        ploidy = 2
        if v.genotypes[0] == [-1, True] or v.genotypes[0] == [-1, False]: continue
        if karyotype == 'XY' and (chrom == 'chrX' or chrom == 'chrY'): ploidy = 1
        # v.genotypes is a list of lists, with genotype of each sample
        # for one sample [allele1, allele2, phased?]
        if tool == "straglr":
            if v.genotypes[0] == [0, False]:
                genotypes = [0, 0]
            elif v.genotypes[0] == [1, False]:
                genotypes = [1, 1]
            else: genotypes = v.genotypes[0][:2]
            for gt in genotypes[:ploidy]:
                try:
                    gt = int(gt)
                    if gt == -1: tool_genotype.append(False)
                    else: tool_genotype.append(alleles[gt])
                except ValueError: tool_genotype.append(False)
        else:
            for gt in v.genotypes[0][:ploidy]:
                try:
                    gt = int(gt)
                    if gt == -1: tool_genotype.append(False)
                    else:
                        if alleles[gt] == '<DEL>' or alleles[gt] == '*': tool_genotype.append("")
                        else: tool_genotype.append(alleles[gt])
                except ValueError: tool_genotype.append(False)

        if False in tool_genotype: continue

        tool_genotype = sorted(tool_genotype, key=lambda x: (x is False, len(x)))
        tool_genotypes[bed_key] = tool_genotype
        locus_keymap[bed_key]   = f'{chrom}-{start}-{end}'
        if (bed_key in locus_motif and locus_motif[bed_key] == '') or bed_key not in locus_motif: locus_motif[bed_key]    = motif

    return bed_entries, tool_genotypes, locus_keymap


def sort_bed_pybedtools(input_bed, output_bed):
    """
    Sort a BED file using pybedtools and write to a new file.
    Sorting uses BEDTools' default: chrom -> start -> end.

    :param input_bed: Path to input BED file
    :param output_bed: Path to output sorted BED file
    :return: None
    """

    bed = BedTool(input_bed)
    sorted_bed = bed.sort()
    sorted_bed.saveas(output_bed)


def length_difference(tool_genotype, assembly_genotype):
    """
    Calculate the length difference between tool genotype and assembly genotype.

    :param tool_genotype: List of two allele lengths from the tool
    :param assembly_genotype: List of two allele lengths from the assembly
    :return: Tuple of length differences for both alleles
    """

    if not tool_genotype or not assembly_genotype or len(tool_genotype) != 2 or len(assembly_genotype) != 2:
        return (None, None)
    # handle missing alleles encoded as False/None
    if any(x is False or x is None for x in tool_genotype + assembly_genotype):
        return (None, None)

    a0, a1 = tool_genotype
    b0, b1 = assembly_genotype

    # two possible pairings; choose the one with smaller total difference
    d_pair1 = [abs(a0 - b0), abs(a1 - b1)]
    d_pair2 = [abs(a0 - b1), abs(a1 - b0)]

    if (d_pair1[0] + d_pair1[1]) <= (d_pair2[0] + d_pair2[1]):
        return d_pair1, [a0, b0], [a1, b1]
    else:
        return d_pair2, [a0, b1], [a1, b0]


def seq_difference(tool_genotype, assembly_genotype):
    """
    Calculate the sequence difference between tool genotype and assembly genotype.

    :param tool_genotype: List of two allele sequences from the tool
    :param assembly_genotype: List of two allele sequences from the assembly
    :return: Tuple of sequence differences for both alleles
    """

    if not tool_genotype or not assembly_genotype or len(tool_genotype) != 2 or len(assembly_genotype) != 2:
        return (None, None)
    # handle missing alleles encoded as False/None
    if any(x is False or x is None for x in tool_genotype + assembly_genotype):
        return (None, None)

    a0, a1 = tool_genotype
    b0, b1 = assembly_genotype

    # two possible pairings; choose the one with smaller total difference
    d_pair1 = [lv.distance(a0, b0), lv.distance(a1, b1)]
    d_pair2 = [lv.distance(a0, b1), lv.distance(a1, b0)]

    ld_pair1 = [abs(len(a0) - len(b0)), abs(len(a1) - len(b1))]
    ld_pair2 = [abs(len(a0) - len(b1)), abs(len(a1) - len(b0))]

    if (d_pair1[0] + d_pair1[1]) <= (d_pair2[0] + d_pair2[1]):
        return ld_pair1, d_pair1, [a0, b0], [a1, b1]
    else:
        return ld_pair2, d_pair2, [a0, b1], [a1, b0]

def seq_difference_haploid(tool_genotype, assembly_allele):
    """
    Calculate the sequence difference between tool genotype and assembly genotype.

    :param tool_genotype: List of two allele sequences from the tool
    :param assembly_genotype: List of two allele sequences from the assembly
    :return: Tuple of sequence differences for both alleles
    """

    if assembly_allele in tool_genotype:
        return [0], [0], [assembly_allele, assembly_allele]
    
    if len(tool_genotype) == 1:
        tool_allele = tool_genotype[0]
        return [abs(len(tool_allele) - len(assembly_allele))], [lv.distance(tool_allele, assembly_allele)], [tool_allele, assembly_allele]
    
    if len(tool_genotype) == 2:
        min_distance = float('inf')
        min_index = 0
        for i in range(2):
            distance = lv.distance(tool_genotype[i], assembly_allele)
            if distance < min_distance:
                min_distance = distance
                min_index = i
        return [abs(len(tool_genotype[min_index]) - len(assembly_allele))], [min_distance], [tool_genotype[min_index], assembly_allele]


def process_sample(sample_id, vcf, aln, regions, tool, reference, karyotype, output):

    locus_motif = {}
    with open(regions) as fh:
        for line in fh:
            line = line.strip().split('\t')
            line[1] = int(line[1])
            line[2] = int(line[2])
            key = f"{line[0]}-{line[1]}-{line[2]}"
            if tool == "longtr": key = f"{line[0]}-{int(line[1])-1}-{line[2]}"
            locus_motif[key] = line[3]

    mat_aln = pysam.AlignmentFile(aln[0], "rb")
    pat_aln = pysam.AlignmentFile(aln[1], "rb")

    locus_keymap = {}
    bed_entries, tool_genotypes, locus_keymap = process_vcf(vcf, tool, locus_motif, karyotype)

    # creates a temporary bed file of the regions from the VCF file
    # Generate a random integer between 0 and 10,000,000
    random_int = random.randint(0, 10000000)

    # Format as hex (e.g., '0x989680' or padded '00989680')
    hex_code = "{:06x}".format(random_int)
    temp_bed = f"temp_{hex_code}.bed"
    if os.path.exists(f"{temp_bed}.gz"):
        while os.path.exists(f"temp_{random_int}.bed.gz"):
            random_int += 1
        hex_code = "{:06x}".format(random_int)
        temp_bed = f"temp_{hex_code}.bed"
    tmp_tbx = open(temp_bed, 'w')
    for bed in bed_entries:
        tmp_tbx.write(f"{bed[0]}\t{bed[1]}\t{bed[2]}\n")
    tmp_tbx.close()
    sort_bed_pybedtools(temp_bed, temp_bed.replace('.bed', '.sorted.bed'))

    _bgz_bed = temp_bed + ".gz"
    pysam.tabix_compress(temp_bed.replace('.bed', '.sorted.bed'), _bgz_bed, force=True)
    pysam.tabix_index(_bgz_bed, preset="bed", force=True)
    tbx = pysam.TabixFile(_bgz_bed)

    # optional: remove intermediate/uncompressed files
    os.remove(temp_bed.replace('.bed', '.sorted.bed'))
    os.remove(temp_bed)

    assembly_genotypes = get_assembly_genotypes(mat_aln, pat_aln, tbx, karyotype)

    missed_regions = 0
    called_regions = 0
    asm_variant_type = ''
    tool_variant_type = ''

    if tool == "atarva":
        asm_vcf = open(f"{sample_id}.asm.vcf", 'w')
        print("##fileformat=VCFv4.2", file=asm_vcf)
        print("##source=AssemblyGenotyper", file=asm_vcf)
        print("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE", file=asm_vcf)
    for bed_key in tool_genotypes.keys():
        coord_change = 'CHANGED'
        vcf_key = locus_keymap[bed_key]
        if vcf_key == bed_key: coord_change = 'UNCHANGED'
        motif = locus_motif[bed_key]
        if tool == 'vamos': motif = motif.split(',')[0]
        haplogroup = 'NA'
        asm_variant_type = 'NA'
        tool_variant_type = 'NA'
        tool_allele_length = 'NA'
        assembly_allele_length = 'NA'
        length_difference = 'NA'
        lev_distance = 'NA'
        status = 'MISSING'
        asm_lev = ['NA', 'NA']

        ploidy = 2
        if karyotype == 'XY' and (bed_key.split('-')[0] == 'chrX' or bed_key.split('-')[0] == 'chrY'): ploidy = 1

        ref_length = int(vcf_key.split('-')[2]) - int(vcf_key.split('-')[1])

        if vcf_key not in assembly_genotypes:
            for i in range(ploidy):
                print(f"{sample_id}\t{bed_key}\t{motif}\t{len(motif)}\t{ref_length}\t{vcf_key}\t{i+1}\t{asm_variant_type}\t{tool_variant_type}\t{tool_allele_length}", end = "\t", file=output)
                print(f"{assembly_allele_length}\t{length_difference}\t{lev_distance}\t{asm_lev[i]}\t{tool}\t{status}", file=output)
            missed_regions += 1
        else:
            called_regions += 1
            tool_alengths = [len(allele) if allele is not False else None for allele in tool_genotypes[bed_key]]
            asm_alengths =  [len(allele) if allele is not False else None for allele in assembly_genotypes[vcf_key]]
            
            tool_alleles = [allele if allele is not False else None for allele in tool_genotypes[bed_key]]
            asm_alleles =  [allele if allele is not False else None for allele in assembly_genotypes[vcf_key]]
            ref_allele = reference.fetch(vcf_key.split('-')[0], int(vcf_key.split('-')[1]), int(vcf_key.split('-')[2]))
            # if tool == 'vamos':
            #     ref_allele = reference.fetch(vcf_key.split('-')[0], int(vcf_key.split('-')[1]) + 1, int(vcf_key.split('-')[2]) + 1)

            asm_alts = []; asm_gt = ""; asm_gidx = 1
            for allele in asm_alleles[:ploidy]:
                if allele != ref_allele:
                    asm_alts.append(allele)
                    asm_gt += str(asm_gidx) + ('|' if ploidy == 2 else '')
                    asm_gidx += 1
                else:
                    asm_gt += '0' + ('|' if ploidy == 2 else '')
            if asm_gt.endswith('|'): asm_gt = asm_gt[:-1]
            
            if tool == "atarva": print(vcf_key.split('-')[0], int(vcf_key.split('-')[1]) + 1, vcf_key, ref_allele,','.join(asm_alts), "0", ".",f"LOCUS={vcf_key}","GT",asm_gt, sep='\t', file=asm_vcf)

            pair1 = ['NA', 'NA']
            pair2 = ['NA', 'NA']
            if ploidy == 2:
                if ref_allele == asm_alleles[0] and ref_allele == asm_alleles[1]: asm_variant_type = 'REF-HOM'
                elif ref_allele == asm_alleles[0] or ref_allele == asm_alleles[1]: asm_variant_type = 'REF-HET'
                elif asm_alleles[0] == asm_alleles[1]: asm_variant_type = 'ALT-HOM'
                elif asm_alleles[0] != asm_alleles[1]: asm_variant_type = 'ALT-HET'

                if tool == 'straglr':
                    if len(ref_allele) == len(tool_alleles[0]) and len(ref_allele) == len(tool_alleles[1]): tool_variant_type = 'REF-HOM'
                    elif len(ref_allele) == len(tool_alleles[0]) or len(ref_allele) == len(tool_alleles[1]): tool_variant_type = 'REF-HET'
                    elif len(tool_alleles[0]) == len(tool_alleles[1]): tool_variant_type = 'ALT-HOM'
                    elif len(tool_alleles[0]) != len(tool_alleles[1]): tool_variant_type = 'ALT-HET'
                else:
                    if ref_allele == tool_alleles[0] and ref_allele == tool_alleles[1]: tool_variant_type = 'REF-HOM'
                    elif ref_allele == tool_alleles[0] or ref_allele == tool_alleles[1]: tool_variant_type = 'REF-HET'
                    elif tool_alleles[0] == tool_alleles[1]: tool_variant_type = 'ALT-HOM'
                    elif tool_alleles[0] != tool_alleles[1]: tool_variant_type = 'ALT-HET'

                ldiff, sdiff, pair1, pair2 = seq_difference(tool_alleles, asm_alleles)
                asm_lev = [lv.distance(pair1[1], ref_allele), lv.distance(pair2[1], ref_allele)]
            elif ploidy == 1:
                asm_allele = asm_alleles[0]
                if asm_allele == ref_allele: asm_variant_type = 'REF-HEM'
                else: asm_variant_type = 'ALT-HEM'
                
                ldiff, sdiff, pair1 = seq_difference_haploid(tool_alleles, asm_allele)
                if tool_alleles[0] == ref_allele: tool_variant_type = 'REF-HEM'
                else: tool_variant_type = 'ALT-HEM'
                asm_lev = [lv.distance(pair1[1], ref_allele)]

            for i, _ in enumerate(tool_alleles):
                haplogroup = i + 1
                pair = pair1 if i == 0 else pair2
                length_difference = len(pair[0]) - len(pair[1])
                if length_difference == 0: status = 'MATCH'
                elif abs(length_difference) == 1: status = 'ONE-OFF'
                elif abs(length_difference) <= len(motif): status = 'MOTIF-OFF'
                else: status = 'MISMATCH'
                print(sample_id, bed_key, motif, len(motif), ref_length, vcf_key, haplogroup, asm_variant_type, tool_variant_type, len(pair[0]), end = "\t", sep='\t', file=output)
                print(len(pair[1]), length_difference, sdiff[i], asm_lev[i], tool, status, sep='\t', file=output)

    if tool == "atarva": asm_vcf.close()
    if os.path.exists(_bgz_bed):
        os.remove(_bgz_bed)
    if os.path.exists(_bgz_bed + ".tbi"):
        os.remove(_bgz_bed + ".tbi")
    if os.path.exists(temp_bed):
        os.remove(temp_bed)
    mat_aln.close()
    pat_aln.close()


def main():
    args = parse_args()
    if args.reference is None:
        print("Error: Reference genome FASTA file must be provided using --reference.", file=sys.stderr)
        sys.exit(1)
    reference = pysam.FastaFile(args.reference)
    output = args.output

    print(f"sample_id\tcatalog_locus\tmotif\tmotif_length\tref_len\tvcf_locus\thaplogroup\tasm_vtype\ttool_vtype\ttool_len", end="\t", file=output)
    print("asm_len\tlen_diff\ttool_lev\tasm_lev\ttool\tstatus", file=output)

    if args.input:
        for line in args.input:
            line = line.strip().split('\t')
            sample_id, vcf, mat_aln, pat_aln, karyotype = line
            aln = [mat_aln, pat_aln]
            process_sample(sample_id, vcf, aln, args.regions, args.tool, reference, karyotype, args.output)
    else:
        vcf = args.vcf
        aln = args.aln
        tool = args.tool
        karyotype = args.karyotype
        process_sample(args.sample_id, vcf, aln, args.regions, tool, reference, karyotype, output)
    
    output.close()


if __name__ == "__main__":
    main()

